# Generated by Django 3.2.6 on 2021-09-06 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstpage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='listing_id',
            field=models.IntegerField(default=222),
            preserve_default=False,
        ),
    ]
