# Generated by Django 3.2.6 on 2021-09-06 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstpage', '0002_product_listing_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='listing_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
