# Generated by Django 3.2.6 on 2021-09-06 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstpage', '0004_product_productlink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='productLink',
            field=models.CharField(default='#', max_length=200),
            preserve_default=False,
        ),
    ]
