# Generated by Django 3.2.6 on 2021-09-06 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstpage', '0005_alter_product_productlink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='productLink',
            field=models.URLField(),
        ),
    ]
